<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Convoy extends Model{

    protected $fillable = [
        'title',
        'start_city',
        'start_company',
        'rest_city',
        'rest_company',
        'finish_city',
        'finish_company',
        'server',
        'communication',
        'communication_link',
        'communication_channel',
        'lead',
        'truck',
        'truck_tuning',
        'truck_paint',
        'trailer',
        'trailer_tuning',
        'trailer_paint',
        'cargo',
        'alt_trailer',
        'alt_trailer_tuning',
        'alt_trailer_paint',
        'alt_cargo',
        'dlc',
    ];

    protected $casts = [
        'visible' => 'boolean',
        'dlc' => 'array',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
        'start_time'
    ];

    public function isUpcoming(){
        $now = Carbon::now();
        return $now->subMinutes(45)->lessThan($this->start_time);
    }

    public function getCommunicationLink(){
        $href = '';
        if($this->communication === 'TeamSpeak 3'){
            $href .= 'https://invite.teamspeak.com/';
        }
        return $href . $this->communication_link;
    }

    public function citiesList($game){
        $cities = [
            'ets2' => [
                'Абердин (Aberdeen)' => '',
                'Амстердам (Amsterdam)' => '',
                'Берлин (Berlin)' => '',
                'Берн (Bern)' => '',
                'Бирмингем (Birmingham)' => '',
                'Братислава (Bratislava)' => '',
                'Бремен (Bremen)' => '',
                'Брно (Brno)' => '',
                'Брюссель (Brussel)' => '',
                'Вена (Wien)' => '',
                'Венеция (Venezia)' => '',
                'Верона (Verona)' => '',
                'Вроцлав (Wrocław)' => '',
                'Гамбург (Hamburg)' => '',
                'Ганновер (Hannover)' => '',
                'Гласго (Glasgow)' => '',
                'Грац (Graz)' => '',
                'Гримсби (Grimsby)' => '',
                'Гронинген (Groningen)' => '',
                'Дижон (Dijon)' => '',
                'Дортмунд (Dortmund)' => '',
                'Дрезден (Dresden)' => '',
                'Дувр (Dover)' => '',
                'Дуйсбург (Duisburg)' => '',
                'Дюсельдорф (Dusseldorf)' => '',
                'Европорт (Europort)' => '',
                'Женева (Geneve)' => '',
                'Зальцбург (Salsburg)' => '',
                'Инсбрук (Innsbruck)' => '',
                'Кале (Calais)' => '',
                'Кардифф (Cardiff)' => '',
                'Карлайл (Carlisle)' => '',
                'Кассель (Kassel)' => '',
                'Кембридж (Сambridge)' => '',
                'Киль (Kiel)' => '',
                'Клагенфурт-ам-Вёртерзе (Klagenfurt am Wörthersee)' => '',
                'Кёльн (Köln)' => '',
                'Лейпциг (Leipzig)' => '',
                'Ливерпуль (Liverpool)' => '',
                'Лилль (Lille)' => '',
                'Линц (Linz)' => '',
                'Лион (Lyon)' => '',
                'Лондон (London)' => '',
                'Льеж (Liège)' => '',
                'Люксембург (Luxembourg)' => '',
                'Магдебург (Magdeburg)' => '',
                'Мангейм (Mannheim)' => '',
                'Манчестер (Manchester)' => '',
                'Мец (Metz)' => '',
                'Милан (Milano)' => '',
                'Мюнхен (München)' => '',
                'Ньюкасл-апон-Тайн (Newcastle upon Tyne)' => '',
                'Нюрнберг (Nürnberg)' => '',
                'Оснабрюк (Osnabrück)' => '',
                'Париж (Paris)' => '',
                'Плимут (Plymouth)' => '',
                'Познань (Poznań)' => '',
                'Прага (Praha)' => '',
                'Реймс (Reims)' => '',
                'Росток (Rostock)' => '',
                'Роттердам (Rotterdam)' => '',
                'Саутгемптон (Southampton)' => '',
                'Страсбург (Strassbourg)' => '',
                'Суонси (Swansea)' => '',
                'Травемюнде (Travemünde)' => '',
                'Турин (Torino)' => '',
                'Филикстоу (Felixstow)' => '',
                'Франкфурт-на-майне (Frankfurt am Main)' => '',
                'Халл (Hull)' => '',
                'Харидж (Harwich)' => '',
                'Цюрих (Zürich)' => '',
                'Шеффилд (Sheffield)' => '',
                'Штутгарт (Stuttgart)' => '',
                'Щецин (Szczecin)' => '',
                'Эдинбург (Edinburgh)' => '',
                'Эймёйден (IJmuiden)' => '',
                'Эрфурт (Erfurt)' => '',

                'Банска-Бистрица (Banská Bystrica)' => 'Going East!',
                'Белосток (Białystok)' => 'Going East!',
                'Будапешт (Budapest)' => 'Going East!',
                'Варшава (Warszawa)' => 'Going East!',
                'Гданьск (Gdańsk)' => 'Going East!',
                'Дебрецен (Debrecen)' => 'Going East!',
                'Катовице (Katowice)' => 'Going East!',
                'Кошице (Košice)' => 'Going East!',
                'Краков (Kraków)' => 'Going East!',
                'Лодзь (Łódź)' => 'Going East!',
                'Люблин (Lublin)' => 'Going East!',
                'Ольштын (Olsztyn)' => 'Going East!',
                'Острава (Ostrava)' => 'Going East!',
                'Печ (Pécs)' => 'Going East!',
                'Сегед (Szeged)' => 'Going East!',

                'Берген (Bergen)' => 'Scandinavia',
                'Векшё (Växjö)' => 'Scandinavia',
                'Вестерос (Västreås)' => 'Scandinavia',
                'Гдыня (Gdynia)' => 'Scandinavia',
                'Гедсер (Gedser)' => 'Scandinavia',
                'Гётеборг (Göteborg)' => 'Scandinavia',
                'Йёнчёпинг (Jönköping)' => 'Scandinavia',
                'Кальмар (Kalmar)' => 'Scandinavia',
                'Капельшер (Kapellskär)' => 'Scandinavia',
                'Карлскруна (Karlskrona)' => 'Scandinavia',
                'Копенгаген (København)' => 'Scandinavia',
                'Кристиансанн (Kristiansand)' => 'Scandinavia',
                'Линчёпинг (Linköping)' => 'Scandinavia',
                'Мальмё (Malmö)' => 'Scandinavia',
                'Нюнесхамн (Nynäshamn)' => 'Scandinavia',
                'Оденсе (Odense)' => 'Scandinavia',
                'Ольборг (Aalborg)' => 'Scandinavia',
                'Осло (Oslo)' => 'Scandinavia',
                'Ставангер (Stavanger)' => 'Scandinavia',
                'Стокгольм (Stockholm)' => 'Scandinavia',
                'Сёдертелье (Södertälje)' => 'Scandinavia',
                'Треллеборг (Trelleborg)' => 'Scandinavia',
                'Уппсала (Uppsala)' => 'Scandinavia',
                'Фредериксхавн (Frederikshavn)' => 'Scandinavia',
                'Хельсинблог (Helsingborg)' => 'Scandinavia',
                'Хиртсхальс (Hirtshals)' => 'Scandinavia',
                'Эребру (Örebro)' => 'Scandinavia',
                'Эсбьерг (Esbjerg)' => 'Scandinavia',

                'Аяччо (Ajaccio)' => 'Vive la France!',
                'Бастия (Bastia)' => 'Vive la France!',
                'Бонифачо (Bonifacio)' => 'Vive la France!',
                'Бордо (Bordeaux)' => 'Vive la France!',
                'Брест (Brest)' => 'Vive la France!',
                'Бурже (Le Bourget)' => 'Vive la France!',
                'Гавр (Le Havre)' => 'Vive la France!',
                'Гольфеш (Golfech)' => 'Vive la France!',
                'Кальви (Calvi)' => 'Vive la France!',
                'Клермон-Ферран (Clermont-Ferrand)' => 'Vive la France!',
                'Л\'Иль-Рус (L\'Île-Rousse)' => 'Vive la France!',
                'Ла-Рошель (La Rochelle)' => 'Vive la France!',
                'Ле-Ман (Le Mans)' => 'Vive la France!',
                'Лимож (Limoges)' => 'Vive la France!',
                'Марсель (Marseille)' => 'Vive la France!',
                'Монпелье (Montpellier)' => 'Vive la France!',
                'Нант (Nantes)' => 'Vive la France!',
                'Ницца (Nice)' => 'Vive la France!',
                'Палюэль (Paluel)' => 'Vive la France!',
                'Порто-Веккьо (Porto-Vecchio)' => 'Vive la France!',
                'Ренн (Rennes)' => 'Vive la France!',
                'Роскоф (Roscoff)' => 'Vive la France!',
                'Сен-Лоран (Saint-Laurent)' => 'Vive la France!',
                'Сент-Альбан-дю-Рон (Saint-Alban-du-Rhône)' => 'Vive la France!',
                'Сиво (Civaux)' => 'Vive la France!',
                'Тулуза (Toulouse)' => 'Vive la France!',

                'Анкона (Ancona)' => 'Italia',
                'Бари (Bari)' => 'Italia',
                'Болонья (Bologna)' => 'Italia',
                'Вилла-Сан-Джованни (Villa San Giovanni)' => 'Italia',
                'Генуя (Genova)' => 'Italia',
                'Кальяри (Cagliari)' => 'Italia',
                'Кассино (Cassino)' => 'Italia',
                'Катандзаро (Catanzaro)' => 'Italia',
                'Катания (Catania)' => 'Italia',
                'Ливорно (Livorno)' => 'Italia',
                'Мессина (Messina)' => 'Italia',
                'Неаполь (Napoli)' => 'Italia',
                'Ольбия (Olbia)' => 'Italia',
                'Палермо (Palermo)' => 'Italia',
                'Парма (Parma)' => 'Italia',
                'Пескара (Pescara)' => 'Italia',
                'Рим (Roma)' => 'Italia',
                'Сассари (Sassari)' => 'Italia',
                'Судзара (Suzzara)' => 'Italia',
                'Таранто (Taranto)' => 'Italia',
                'Терни (Terni)' => 'Italia',
                'Флоренция (Firenze)' => 'Italia',

                'Валмиера (Valmiera)' => 'Beyond The Baltic Sea',
                'Вентспилс (Ventspils)' => 'Beyond The Baltic Sea',
                'Вильнюс (Vilnius)' => 'Beyond The Baltic Sea',
                'Выборг' => 'Beyond The Baltic Sea',
                'Даугавпилс (Daugavpils)' => 'Beyond The Baltic Sea',
                'Калининград' => 'Beyond The Baltic Sea',
                'Каунас (Kaunas)' => 'Beyond The Baltic Sea',
                'Клайпеда (Klaipėda)' => 'Beyond The Baltic Sea',
                'Котка (Kotka)' => 'Beyond The Baltic Sea',
                'Коувола (Kouvola)' => 'Beyond The Baltic Sea',
                'Кунда (Kunda)' => 'Beyond The Baltic Sea',
                'Лахти (Lahti)' => 'Beyond The Baltic Sea',
                'Лиепая (Liepāja)' => 'Beyond The Baltic Sea',
                'Ловийса (Loviisa)' => 'Beyond The Baltic Sea',
                'Луга' => 'Beyond The Baltic Sea',
                'Мажейкяй (Mažeikiai)' => 'Beyond The Baltic Sea',
                'Наантали (Naantali)' => 'Beyond The Baltic Sea',
                'Нарва (Narva)' => 'Beyond The Baltic Sea',
                'Олкилуото (Olkiluoto)' => 'Beyond The Baltic Sea',
                'Палдиски (Paldiski)' => 'Beyond The Baltic Sea',
                'Паневежис (Panevėžys)' => 'Beyond The Baltic Sea',
                'Пори (Pori)' => 'Beyond The Baltic Sea',
                'Псков' => 'Beyond The Baltic Sea',
                'Пярну (Pärnu)' => 'Beyond The Baltic Sea',
                'Резекне (Rēzekne)' => 'Beyond The Baltic Sea',
                'Рига (Rīga)' => 'Beyond The Baltic Sea',
                'Санкт-Петербург' => 'Beyond The Baltic Sea',
                'Сосновый бор' => 'Beyond The Baltic Sea',
                'Таллин (Tallinn)' => 'Beyond The Baltic Sea',
                'Тампере (Tampere)' => 'Beyond The Baltic Sea',
                'Тарту (Tartu)' => 'Beyond The Baltic Sea',
                'Турку (Turku)' => 'Beyond The Baltic Sea',
                'Утена (Utena)' => 'Beyond The Baltic Sea',
                'Хельсинки (Helsinki)' => 'Beyond The Baltic Sea',
                'Шяуляй (Šiauliai)' => 'Beyond The Baltic Sea',

                'Бакэу (Bacău)' => 'Road To The Black Sea',
                'Брашов (Brașov)' => 'Road To The Black Sea',
                'Бургас' => 'Road To The Black Sea',
                'Бухарест (București)' => 'Road To The Black Sea',
                'Варна' => 'Road To The Black Sea',
                'Велико Търново' => 'Road To The Black Sea',
                'Галац (Galați)' => 'Road To The Black Sea',
                'Карлово' => 'Road To The Black Sea',
                'Клуж-Напока (Cluj-Napoca)' => 'Road To The Black Sea',
                'Козлодуй' => 'Road To The Black Sea',
                'Констанца (Constanța)' => 'Road To The Black Sea',
                'Крайова (Craiova)' => 'Road To The Black Sea',
                'Кэлэраши (Călărași)' => 'Road To The Black Sea',
                'Мангалия (Mangalia)' => 'Road To The Black Sea',
                'Перник' => 'Road To The Black Sea',
                'Пирдоп' => 'Road To The Black Sea',
                'Питешти (Pitești)' => 'Road To The Black Sea',
                'Плевен' => 'Road To The Black Sea',
                'Пловдив' => 'Road To The Black Sea',
                'Решица (Reșița)' => 'Road To The Black Sea',
                'Русе' => 'Road To The Black Sea',
                'София' => 'Road To The Black Sea',
                'Стамбул (İstanbul)' => 'Road To The Black Sea',
                'Текирдаг (Tekirdağ)' => 'Road To The Black Sea',
                'Тимишоара (Timișoara)' => 'Road To The Black Sea',
                'Тыргу-Муреш (Târgu Mureș)' => 'Road To The Black Sea',
                'Хунедоара (Hunedoara)' => 'Road To The Black Sea',
                'Чернаводэ (Cernavodă)' => 'Road To The Black Sea',
                'Эдирне (Edirne)' => 'Road To The Black Sea',
                'Яссы (Iași)' => 'Road To The Black Sea',
            ],
            'ats' => [

            ]
        ];
    }

}
